name: Check Figma Script Rewrite

on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  capture:
    runs-on: ubuntu-latest

    env:
      FIGMA_EMAIL: ${{ secrets.FIGMA_EMAIL }}
      FIGMA_PASSWORD: ${{ secrets.FIGMA_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run capture script
        run: pnpm exec tsx scripts/capture.ts
